### ISSUE TITLE
Add Mach-1 file read function

### ISSUE THREAD

**Issue by BastianHartmann** [CANTERhm/Canter_Matlab_Library#10]
### Todo items:
- [x] Write a function to read text files from the Mach-1 (Biomomentum)
- [x] Write a function to get the general header information of a Mach-1 file and the segment header information of each segment the file contains.
- [x] Add the ReadMachTextFile function to the button_load_data_Callback of the bihertz_gui.m
- [x] Display the general header information together with the segment header information in the info panel. Note: the segment header information must change in dependency of the currently processed segment (force curve).
